// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenerateCStyleString
{
    internal sealed partial class Vsix
    {
        public const string Id = "GenerateCStyleString.63eb67b4-b158-4d32-a333-3f23b72c44db";
        public const string Name = "Generate a C Style String";
        public const string Description = @"Generate a C Style String.For Example selecet 'MessageBox' in your Editor and click generate you replace 'MessageBox'  to 'char szMessageBox = {'M','e','s','s','a','g','e','B','o','x','\0'};'";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HelloC";
        public const string Tags = "";
    }
}
