// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenerateCStyleString
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GenerateCStyleStringString = "8957af8e-55a8-47e6-abb9-3d74d74048f8";
        public static Guid GenerateCStyleString = new Guid(GenerateCStyleStringString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCtxMenuGroup = 0x0002;
        public const int MyCommand = 0x0100;
    }
}